/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    HelloWorld: typeof import('./src/components/hello-world.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WmLayout: typeof import('./src/components/layout/wm-layout.vue')['default']
    WmLayoutHeader: typeof import('./src/components/layout/wm-layout-header.vue')['default']
    WmLayoutSidebar: typeof import('./src/components/layout/wm-layout-sidebar.vue')['default']
    WuLayoutSidebar: typeof import('./src/components/layout/wu-layout-sidebar.vue')['default']
  }
}
