/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HelloWorld: typeof import('./src/components/hello-world.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WmLayout: typeof import('./src/components/wm/layout/index.vue')['default']
    WmLayoutHeader: typeof import('./src/components/wm/layout/header.vue')['default']
    WmLayoutLogo: typeof import('./src/components/wm/layout/logo.vue')['default']
    WmLayoutSidebar: typeof import('./src/components/wm/layout/sidebar.vue')['default']
  }
}
